[project]
name = 'Decentralized-Airline-Baggage-Tracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.handling-verification]
path = 'contracts/handling-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.location-tracking]
path = 'contracts/location-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.luggage-registration]
path = 'contracts/luggage-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
